### ISSUE TITLE
Please provide a way to opt out from intercepting singals

### ISSUE THREAD

**Issue by ytimenkov** [catchorg/Catch2#2043]
Please see #boostorg/test/issues/285 for detailed reasoning.

Catch does some things differently, but I did find a bunch of issues related to this and even though you can try to fix each particular case, I'd rather like the UT framework not interfere with signal handling at all as it can't be made 100% reliable (well, unless you run an external process, I guess...).

I've got crash like this (it's 1.7 but quickly examining current code suggests that behavior in general is the same):
```
#0  0x00007f9328626989 in raise () from /home/default/el7-image/lib64/libc.so.6
#1  0x00007f9328628098 in abort () from /home/default/el7-image/lib64/libc.so.6
#2  0x00007f932861f8f6 in __assert_fail_base () from /home/default/el7-image/lib64/libc.so.6
#3  0x00007f932861f9a2 in __assert_fail () from /home/default/el7-image/lib64/libc.so.6
#4  0x0000000000641d07 in Catch::CumulativeReporterBase::testCaseEnded (this=0x1809660, testCaseStats=...)
    at ../../../../../../catch/1.7.1/nasdaq/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/catch/catch.hpp:9228
#5  0x00000000006490e7 in Catch::JunitReporter::testCaseEnded (this=0x1809660, testCaseStats=...) at ../../../../../../catch/1.7.1/nasdaq/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/catch/catch.hpp:9893
#6  0x00000000006381bb in Catch::RunContext::handleFatalErrorCondition (this=0x7fff13bdae60, message=...) at ../../../../../../catch/1.7.1/nasdaq/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/catch/catch.hpp:6529
#7  0x0000000000634c73 in Catch::reportFatal (message=...) at ../../../../../../catch/1.7.1/nasdaq/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/catch/catch.hpp:6120
#8  0x0000000000634dba in Catch::FatalConditionHandler::handleSignal (sig=6) at ../../../../../../catch/1.7.1/nasdaq/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/catch/catch.hpp:6265
#9  <signal handler called>
#10 0x00007f9328626989 in raise () from /home/default/el7-image/lib64/libc.so.6
#11 0x00007f9328628098 in abort () from /home/default/el7-image/lib64/libc.so.6
#12 0x00007f9328667197 in __libc_message () from /home/default/el7-image/lib64/libc.so.6
#13 0x00007f932866e56d in _int_free () from /home/default/el7-image/lib64/libc.so.6
```

**Comment by horenmar** [comment]
[Please read the documentation](https://github.com/catchorg/Catch2/blob/master/docs/configuration.md#other-toggles)?

**Comment by ytimenkov** [comment]
Thanks! So it was indeed fixed in recent versions 👍
